/**
 * Stable, machine-readable API error codes. Clients switch on these; the
 * accompanying `message` is for display only and may change.
 */
export const ErrorCode = {
  // Generic
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  /** The platform is in maintenance mode; retry later (see Retry-After). */
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',

  // Authentication
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Domain
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  AGENT_PROFILE_INCOMPLETE: 'AGENT_PROFILE_INCOMPLETE',
  AGENT_NOT_VERIFIED: 'AGENT_NOT_VERIFIED',
  AGENT_RESTRICTED: 'AGENT_RESTRICTED',
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  PROPERTY_INCOMPLETE: 'PROPERTY_INCOMPLETE',
  PROPERTY_LOCKED: 'PROPERTY_LOCKED',
  INVALID_FILE: 'INVALID_FILE',

  // Bookings & payments
  PROPERTY_NOT_BOOKABLE: 'PROPERTY_NOT_BOOKABLE',
  DATES_UNAVAILABLE: 'DATES_UNAVAILABLE',
  BOOKING_PRICE_CHANGED: 'BOOKING_PRICE_CHANGED',
  BOOKINGS_NOT_OPEN: 'BOOKINGS_NOT_OPEN',
  BOOKING_HOLD_EXPIRED: 'BOOKING_HOLD_EXPIRED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',

  // Subscriptions
  /** The plan does not exist or is not offered. */
  PLAN_NOT_AVAILABLE: 'PLAN_NOT_AVAILABLE',
  /** A plan change is already paid for and waiting to start. */
  SUBSCRIPTION_CHANGE_SCHEDULED: 'SUBSCRIPTION_CHANGE_SCHEDULED',
  /** No default (free) plan is configured, so allowances cannot be resolved. */
  PLANS_NOT_CONFIGURED: 'PLANS_NOT_CONFIGURED',

  // Communication
  /** The conversation is closed by a moderator: no new messages. */
  CONVERSATION_CLOSED: 'CONVERSATION_CLOSED',
  /** The message can no longer be changed (deleted, system or past the edit window). */
  MESSAGE_NOT_EDITABLE: 'MESSAGE_NOT_EDITABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
